services:
  ollama-rag-llm-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-rag-llm-model
    hostname: ollama-rag-llm-model
    environment:
        - OLLAMA_HOST="0.0.0.0:11434"
        - MODEL=${OLLAMA_LLM_MODEL}
        - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION}
        - ROC_ENABLE_PRE_VEGA=1
        - HIP_VISIBLE_DEVICES=0
    tty: true
    privileged: true
    devices:
      - /dev/kfd
      - /dev/dri
    #ports:
    #  - "${HOST_IP}:11434:11434"
    volumes:
      - "${OLLAMA_DATA}:/root/.ollama"

  ollama-rag-embed-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-rag-embed-model
    hostname: ollama-rag-embed-model
    environment:
      - OLLAMA_HOST="0.0.0.0:11434"
      - MODEL=${OLLAMA_EMBED_MODEL}
      - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION}
      - ROC_ENABLE_PRE_VEGA=1
      - HIP_VISIBLE_DEVICES=0
    tty: true
    privileged: true
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - "${OLLAMA_DATA}:/root/.ollama"

  ollama-rag-qdrant:
    image: qdrant/qdrant
    container_name: ollama-rag-qdrant
    hostname: ollama-rag-qdrant
    volumes:
      - "${QDRANT_DATA}:/qdrant/storage"

  ollama-rag-anythingllm:
    image: mintplexlabs/anythingllm:latest
    container_name: ollama-rag-anythingllm
    hostname: ollama-rag-anythingllm
    depends_on:
      - ollama-rag-llm-model
      - ollama-rag-embed-model
      - ollama-rag-qdrant
    cap_add:
      - SYS_ADMIN
    environment:
      - LLM_PROVIDER=ollama
      - EMBEDDING_MODEL_PREF=nomic-embed-text:latest
      - OLLAMA_BASE_PATH=http://ollama-rag-llm-model:11434
      - OLLAMA_MODEL_PREF=llama3.1:8b
      - OLLAMA_MODEL_TOKEN_LIMIT=4096
      - OLLAMA_PERFORMANCE_MODE=base
      - OLLAMA_KEEP_ALIVE_TIMEOUT=300
      - EMBEDDING_ENGINE=ollama
      - EMBEDDING_BASE_PATH=http://ollama-rag-embed-model:11434
      - EMBEDDING_MODEL_MAX_CHUNK_LENGTH=8192
      - VECTOR_DB=qdrant
      - QDRANT_ENDPOINT=http://ollama-rag-qdrant:6333
      - STORAGE_DIR=/app/server/storage
      - SERVER_PORT=${HOST_PORT}
    ports:
      - "${HOST_IP}:${HOST_PORT}:${HOST_PORT}"
    volumes:
      - "${ANYLLM_DATA}/storage:/app/server/storage"
      - "${ANYLLM_DATA}/.env:/app/server/.env"
