services:
  ollama-llm-model:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-llm-model
    hostname: ollama-llm-model
    environment:
        - OLLAMA_HOST="0.0.0.0:11434"
        - MODEL=${OLLAMA_LLM_MODEL}
        - HSA_OVERRIDE_GFX_VERSION=${HSA_OVERRIDE_GFX_VERSION}
        - ROC_ENABLE_PRE_VEGA=1
        - HIP_VISIBLE_DEVICES=0
    tty: true
    privileged: true
    devices:
      - /dev/kfd
      - /dev/dri
    #ports:
    #  - "${HOST_IP}:11434:11434"
    volumes:
      - "${OLLAMA_DATA}:/root/.ollama"

  ollama-open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-open-webui
    hostname: ollama-open-webui
    depends_on:
      - ollama-llm-model
    environment:
      - 'OLLAMA_BASE_URL=http://ollama-llm-model:11434'
      - 'WEBUI_SECRET_KEY='
    #extra_hosts:
    #  - host.docker.internal:host-gateway
    ports:
      - "${HOST_IP}:${HOST_PORT}:8080"
    volumes:
      - "${WEBUI_DATA}:/app/backend/data"

